---
- hosts: all
  become: true
  become_method: sudo
  tasks:

  - name: add ansible ppa
    apt_repository:
      repo: 'ppa:ansible/ansible'

  - name: apt-get update && install ansible
    apt:
      update_cache: yes
      name: ansible
      state: present
